// English interface text and verified paper explanations.
window.HOMEPAGE_CONTENT = {
  "ui": {
    "skip": "Skip to content",
    "navAbout": "About",
    "navResearch": "Research",
    "navPapers": "Publications",
    "navContact": "Contact",
    "navLabel": "Main navigation",
    "email": "Email",
    "eyebrow": "COMPUTER VISION & MULTIMODAL LEARNING",
    "researchFocus": "RESEARCH FOCUS",
    "focus": "Reliable multimodal learning and perception.",
    "explore": "Explore my work",
    "researchTitle": "Research interests",
    "papersTitle": "Selected publications",
    "papersCount": "3 papers",
    "contactTitle": "Contact",
    "backTop": "Back to top",
    "research1": "Robust multimodal fusion",
    "research1Text": "Task-aware routing and correction for missing, degraded, and conflicting modalities.",
    "research2": "3D & cooperative perception",
    "research2Text": "Reliable sensor fusion and information sharing across cameras, LiDAR, and UAV agents.",
    "research3": "Visual evidence & model reliability",
    "research3Text": "Understanding and improving how vision-language models use evidence in their decisions.",
    "preprint": "arXiv preprint",
    "acceptedNote": "Acceptance reported in the arXiv Comments field",
    "problem": "The problem",
    "method": "The approach",
    "result": "Key result",
    "viewFigure": "Enlarge figure",
    "originalFigure": "Original figure",
    "evidence": "Result source",
    "close": "Close",
    "figureDialog": "Paper figure",
    "citation": "BibTeX",
    "imageNote": "Original paper figure; click to enlarge."
  },
  "papers": [
    {
      "key": "routing",
      "id": "2608.15261",
      "date": "August 2026",
      "accepted": false,
      "authors": [
        "Haifa Zhang",
        "Yijing Wang",
        "Haoyu Wang",
        "Zheng Li",
        "Zhiqiang Zuo"
      ],
      "figure": "./images/routing-framework.png",
      "width": 774,
      "height": 519,
      "figureSource": "https://arxiv.org/html/2608.15261v1/F2.png",
      "resultSource": "https://arxiv.org/html/2608.15261v1#S4.T1",
      "bibKey": "zhang2026boundary",
      "bibTitle": "Boundary-Aligned Contribution Routing for Robust Optical--SAR Object Detection",
      "title": "Boundary-Aligned Contribution Routing for Robust Optical–SAR Object Detection",
      "topic": "Optical–SAR · Robust fusion",
      "takeaway": "Control each modality’s contribution before fusion spreads its errors.",
      "problem": "Optical and SAR images can conflict even when both appear intact. Treating every available modality as useful can introduce negative transfer into the detector.",
      "method": "A Feature Router (FR) or Semantic Router (SR), chosen for the network architecture, adjusts contributions before the first feature mixing operation. The two are alternative implementations trained with detection supervision.",
      "result": "On M4-SAR, adding FR to Simple U-Net raises full-input mAP50 from 58.2% to 64.1% (+5.9 percentage points). Both models use clean training and are evaluated with both modalities present.",
      "metric": "58.2 → 64.1",
      "metricLabel": "mAP50 (%) · M4-SAR · Simple U-Net",
      "caption": "Figure 2. FR acts near the input in frequently fused networks; SR acts before late fusion in dual-backbone networks.",
      "alt": "Original Figure 2: Feature Router for frequently fused networks above, Semantic Router before late fusion below."
    },
    {
      "key": "degunet",
      "id": "2607.12419",
      "date": "July 2026",
      "accepted": true,
      "authors": [
        "Haifa Zhang",
        "Yijing Wang",
        "Peixi Peng",
        "Zhiqiang Zuo"
      ],
      "figure": "./images/degunet-framework.png",
      "width": 820,
      "height": 290,
      "figureSource": "https://arxiv.org/html/2607.12419v1/sec_overall2.png",
      "resultSource": "https://arxiv.org/html/2607.12419v1#S5.T4",
      "bibKey": "zhang2026degunet",
      "bibTitle": "{DeGuNet}: Depth-Guided Ultra-Compact Backbones for Efficient {LiDAR}-Camera 3D Detection",
      "title": "DeGuNet: Depth-Guided Ultra-Compact Backbones for Efficient LiDAR-Camera 3D Detection",
      "topic": "LiDAR–camera · Efficient 3D detection",
      "takeaway": "Use sparse depth to build a smaller image backbone for 3D perception.",
      "problem": "Large image backbones pretrained on 2D tasks add overhead to 3D detection, while sparse LiDAR projections require careful handling of valid geometric cues.",
      "method": "DeGuNet combines depth-completion pretraining, mask-aware feature extraction, and progressive cross-modal guidance to learn compact image features aligned with 3D geometry.",
      "result": "For BEVFusion’23, the A100 efficiency test (batch size 1, 256 × 704 images) reports GPU memory dropping from 20.46 to 6.86 GB (−66.5%) and speed rising from 4.4 to 5.1 FPS. Methods use their recommended inference configurations.",
      "metric": "20.46 → 6.86 GB",
      "metricLabel": "GPU memory · BEVFusion’23 · A100 / batch 1",
      "caption": "Figure 1. RGB images and sparse LiDAR projections guide successive feature stages before BEV transformation and fusion.",
      "alt": "Original Figure 1: RGB and projected LiDAR depth guide three image backbone stages, followed by LiteNeck, LSS, fusion and 3D detection."
    },
    {
      "key": "grace",
      "id": "2605.30983",
      "date": "May 2026",
      "accepted": false,
      "authors": [
        "Haifa Zhang",
        "Yijing Wang",
        "Haoyu Wang",
        "Zheng Li",
        "Zhiqiang Zuo"
      ],
      "figure": "./images/grace-framework.png",
      "width": 829,
      "height": 392,
      "figureSource": "https://arxiv.org/html/2605.30983v1/fig_framework_overview.png",
      "resultSource": "https://arxiv.org/html/2605.30983v1#S4.T1",
      "bibKey": "zhang2026grace",
      "bibTitle": "Can {BEV} Perception Gracefully Degrade under Sensor Failures?",
      "title": "Can BEV Perception Gracefully Degrade under Sensor Failures?",
      "topic": "BEV perception · Sensor reliability",
      "takeaway": "Keep a visual fallback when LiDAR fails.",
      "problem": "Camera–LiDAR BEV detectors can collapse under LiDAR failure, even when cameras still provide usable information.",
      "method": "Grace-BEV uses TrustGate to estimate LiDAR reliability and route between LiDAR-guided and vision-only BEV features. FailSafe Fusion and three-phase training with modality dropout help preserve the fallback.",
      "result": "On nuScenes-R with complete LiDAR dropout, BEVFusion-AD with Grace-BEV reaches 34.7% mAP versus 0.0% for its baseline. On clean data, the same configuration improves mAP from 68.1% to 69.2%.",
      "metric": "0.0 → 34.7",
      "metricLabel": "mAP (%) · BEVFusion-AD · complete LiDAR dropout",
      "caption": "Figure 2. TrustGate routes between depth-guided and vision-only branches; FailSafe Fusion combines their features for detection.",
      "alt": "Original Figure 2: TrustGate controls LiDAR-guided and pure-vision branches, followed by FailSafe Fusion and a detection head."
    }
  ]
};
